// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/supabaseClient.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Return the signed-in DIU StudyBank user's profile (name, roll number, department, batch, section, bio).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("full_name, roll_number, phone_number, section, department, batch, bio, current_semester").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? {}, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-departments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_departments_default = defineTool2({
  name: "list_departments",
  title: "List departments",
  description: "List all academic departments available in DIU StudyBank.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("departments").select("id, name, full_name, description").order("sort_order", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { departments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
var list_courses_default = defineTool3({
  name: "list_courses",
  title: "List courses",
  description: "List courses, optionally filtered by department id and/or semester number.",
  inputSchema: {
    department: z.string().optional().describe("Department id (e.g. 'cse')."),
    semester: z.number().int().min(1).max(12).optional().describe("Semester number 1-12."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ department, semester, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("courses").select("id, code, name, department, semester").order("semester", { ascending: true }).order("code", { ascending: true }).limit(limit ?? 100);
    if (department) q = q.eq("department", department);
    if (semester) q = q.eq("semester", semester);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-files.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
var search_files_default = defineTool4({
  name: "search_files",
  title: "Search study materials",
  description: "Search DIU StudyBank PDFs and notes by title, subject, or course code. Returns files the signed-in user is allowed to see under RLS.",
  inputSchema: {
    query: z2.string().min(1).describe("Free-text query matched against title, subject, and course_code."),
    department: z2.string().optional().describe("Optional department filter (e.g. 'cse')."),
    semester: z2.string().optional().describe("Optional semester filter (e.g. '3')."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, department, semester, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    const like = `%${query.replace(/[%_]/g, (m) => "\\" + m)}%`;
    let q = supabase.from("files").select("id, title, subject, department, semester, course_code, file_type, download_count, upload_date").or(`title.ilike.${like},subject.ilike.${like},course_code.ilike.${like}`).order("upload_date", { ascending: false }).limit(limit ?? 20);
    if (department) q = q.eq("department", department);
    if (semester) q = q.eq("semester", semester);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { files: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-uploads.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_uploads_default = defineTool5({
  name: "list_my_uploads",
  title: "List my uploads",
  description: "List files uploaded by the signed-in user, newest first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("files").select("id, title, subject, department, semester, course_code, file_type, download_count, upload_date, visibility").eq("uploader_id", ctx.getUserId()).order("upload_date", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { files: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bxumytladoxnoakmkhcf";
var mcp_default = defineMcp({
  name: "diu-studybank-mcp",
  title: "DIU StudyBank",
  version: "0.1.0",
  instructions: "Tools for DIU StudyBank \u2014 a study-material library for Daffodil International University. Use `get_my_profile` for the signed-in user's profile, `list_departments` and `list_courses` to browse the catalog, `search_files` to find PDFs and notes, and `list_my_uploads` to see the user's own contributions. All calls run as the signed-in user under database RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_departments_default, list_courses_default, search_files_default, list_my_uploads_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
